### ISSUE TITLE
Namespacing issues with Down "Node" type

### ISSUE THREAD

**Issue by djstevenson** [johnxnguyen/Down#242] opened 2021-01-23 01:29 UTC
I want to build an Html object using Pointfree's https://github.com/pointfreeco/swift-html 
and this Down package.

The idea was to use Down to parse Markdown, and to use a "visitor" (as you define in DebugVisitor for testing) - as I visit a node, I generate the corresponding Html node (so, rather than doing Markdown -> String, I'm trying to do Markdown -> [Html.Node])

I have a problem with the name spacing - both Html and Down define a Node type.  That's normal - I can specifically refer to their type as Html.Node - but I can't refer to your type as Down.Node

My struct imports both:

```
import Down
import Html
```

Then, a reference to "Node" produces the expected error "'Node' is ambiguous for type lookup in this context", along with:

```
1. Found this candidate (Down.Node)
2. Found this candidate (Html.Node) 
```

If I refer to an html type as Html.Node all is fine. But, despite Swift saying "Down.Node" is a candidate, when I use Down.Node I get 

```
   private func nodeWithChildren(_ node: Down.Node, value: String) -> String {     **x 'Node' is not a member type of 'Down'**
```

I can't seem to get the Down node type namespaced.

Xcode 12.3
Html: 0.3.1 https://github.com/pointfreeco/swift-html
Down: 0.9.4 

(Note, I'm relatively new to Swift, so sorry if I'm just being a bit dumb.  If so, any pointers towards being less dumb would be gratefully received!)

**Comment by djstevenson** [comment] 2021-01-23 01:33
Obviously, my workaround is to render Markdown to a String, then include that as 'raw' in my Pointfree Html struct. But I was kinda hoping to get the full safety etc of their library while writing some content in Markdown.

**Comment by djstevenson** [comment] 2021-01-23 02:05
I'll put together a minimal project to illustrate the apparent problem, soon.

**Comment by johnxnguyen** [comment] 2021-01-23 12:23
Hey @djstevenson , thanks for getting in touch and for the nice example repo. So this is an interesting problem that I've never come across before. The source of the problem is that the Down module contains a public type called `Down` which is confusing Xcode.

Consider the following code:

```swift
// Down is the module name
import Down

// You'd think that Down here is referring to the module, but it's actually
// referring to a struct called Down within the Down module. If you cmd + click
// on the word Down you'll see the definition of the struct.
typealias DownNode = Down.Node
```

You're getting the error "Node is not a member type of Down" because Xcode sees that the struct called `Down` doesn't have a nested type called `Node`.

Unfortunately I couldn't figure out a way for Xcode to refer to the module rather than the struct, without having to change the name of the `Down` struct. The good news is that you can easily solve the problem by declaring your typealiases for Down and Html in separate files, such as:

```swift
// In DownAliases.swift
import Down

typealias DownNode = Down.Node
typealias DownText = Down.Text
typealias DownImage = Down.Image
...


// In HtmlAliases.swift
import Html

typealias HtmlNode = Html.Node
...
```

Then you can use those aliases in any other file in your module. 

Try it out and let me know how you go. And lastly, I don't believe there are stupid questions so don't hesitate to ask any more that you might have, I'm happen to help in any way I can.

**Comment by djstevenson** [comment] 2021-01-23 15:30
Thank you for the lightning quick response!

Unfortunately, I'm still seeing the same error in DownAliases.swift - I've pushed a commit implementing your suggestion to my demo repo.

**Comment by djstevenson** [comment] 2021-01-23 16:39
I think I might have cracked it, with DownAliases.swift containing this, which I now realise is probably what you meant to put in your workaround example above:

```
// In DownAliases.swift
import Down

typealias DownNode = Node
typealias DownText = Text
typealias DownImage = Image
```

**Comment by johnxnguyen** [comment] 2021-01-23 20:46
@djstevenson ahhhh yeah, sorry my bad! Indeed I mistyped the code block example, I'll update the comment andl close this issue. Feel free to reach out for anything else!

**Closed by johnxnguyen** 2021-01-23 20:46 UTC
Labels: workaround-available

**Comment by djstevenson** [comment] 2021-01-23 21:13
I really appreciate your help, thank you.

**Comment by kengruven** [comment] 2021-02-24 05:09
Looks like [SR-898](https://bugs.swift.org/browse/SR-898) -- a known language limitation for 5 years.
